#############################################################################
# Generated by PAGE version 5.5
#  in conjunction with Tcl version 8.6
#  Nov 05, 2020 10:11:07 AM CET  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 919x782+399+102
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra45 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 325 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 895 
    vTcl:DefineAlias "$top.fra45" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra45
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Connect 
    vTcl:DefineAlias "$site_3_0.but47" "btn_connect" vTcl:WidgetProc "Toplevel1" 1
    bind $site_3_0.but47 <Button-1> {
        lambda e: p2p_connection(e)
    }
    checkbutton $site_3_0.che48 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -justify left -text {Give Bootstrap} -variable che48 
    vTcl:DefineAlias "$site_3_0.che48" "bootstrap_check" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent49 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 684 
    vTcl:DefineAlias "$site_3_0.ent49" "boostrap_entry" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex51 \
        -background white -font TkTextFont -foreground black -height 34 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 873 -wrap word 
    $site_3_0.tex51 configure -font "TkTextFont"
    $site_3_0.tex51 insert end text
    vTcl:DefineAlias "$site_3_0.tex51" "my_ip_text" vTcl:WidgetProc "Toplevel1" 1
    text $site_3_0.tex52 \
        -background white -font TkTextFont -foreground black -height 143 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 873 -wrap word 
    $site_3_0.tex52 configure -font "TkTextFont"
    $site_3_0.tex52 insert end text
    vTcl:DefineAlias "$site_3_0.tex52" "all_agent_text" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {My IP address:} 
    vTcl:DefineAlias "$site_3_0.lab53" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {All Online Agents:} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.062 -width 67 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che48 \
        -in $site_3_0 -x 0 -relx 0.089 -y 0 -rely 0.062 -width 0 \
        -relwidth 0.118 -height 0 -relheight 0.105 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent49 \
        -in $site_3_0 -x 0 -relx 0.212 -y 0 -rely 0.062 -width 684 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tex51 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.308 -width 0 \
        -relwidth 0.975 -height 0 -relheight 0.105 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tex52 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.523 -width 0 \
        -relwidth 0.975 -height 0 -relheight 0.44 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.19 -width 0 \
        -relwidth 0.105 -height 0 -relheight 0.07 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.431 -width 0 \
        -relwidth 0.12 -height 0 -relheight 0.071 -anchor nw \
        -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 300 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 895 
    vTcl:DefineAlias "$top.fra46" "Frame2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra46
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_3_0.scr60 \
        -background $vTcl(actual_gui_bg) -height 15 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_3_0.scr60" "Scrolledtreeview1" vTcl:WidgetProc "Toplevel1" 1

    .top44.fra46.scr60.01 configure -columns "Col1 Col2 Col3" \
        -height 4
        .top44.fra46.scr60.01 configure -columns {Col1 Col2 Col3}
        .top44.fra46.scr60.01 heading #0 -text {Agents}
        .top44.fra46.scr60.01 heading #0 -anchor center
        .top44.fra46.scr60.01 column #0 -width 444
        .top44.fra46.scr60.01 column #0 -minwidth 30
        .top44.fra46.scr60.01 column #0 -stretch 1
        .top44.fra46.scr60.01 column #0 -anchor w
        .top44.fra46.scr60.01 heading Col1 -text {Visited Pages}
        .top44.fra46.scr60.01 heading Col1 -anchor center
        .top44.fra46.scr60.01 column Col1 -width 141
        .top44.fra46.scr60.01 column Col1 -minwidth 30
        .top44.fra46.scr60.01 column Col1 -stretch 1
        .top44.fra46.scr60.01 column Col1 -anchor w
        .top44.fra46.scr60.01 heading Col2 -text {Target Pages}
        .top44.fra46.scr60.01 heading Col2 -anchor center
        .top44.fra46.scr60.01 column Col2 -width 135
        .top44.fra46.scr60.01 column Col2 -minwidth 30
        .top44.fra46.scr60.01 column Col2 -stretch 1
        .top44.fra46.scr60.01 column Col2 -anchor w
        .top44.fra46.scr60.01 heading Col3 -text {Finded Nodes}
        .top44.fra46.scr60.01 heading Col3 -anchor center
        .top44.fra46.scr60.01 column Col3 -width 139
        .top44.fra46.scr60.01 column Col3 -minwidth 20
        .top44.fra46.scr60.01 column Col3 -stretch 1
        .top44.fra46.scr60.01 column Col3 -anchor w
    place $site_3_0.scr60 \
        -in $site_3_0 -x 0 -relx 0.011 -y 0 -rely 0.087 -width 0 \
        -relwidth 0.981 -height 0 -relheight 0.89 -anchor nw \
        -bordermode ignore 
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Multi-Agent P2P Connection} 
    vTcl:DefineAlias "$top.lab50" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Stats 
    vTcl:DefineAlias "$top.lab57" "Label4" vTcl:WidgetProc "Toplevel1" 1
    frame $top.fra47 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 95 -width 895 
    vTcl:DefineAlias "$top.fra47" "Frame3" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra47
    button $site_3_0.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Browse 
    vTcl:DefineAlias "$site_3_0.but49" "btn_file" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Delete Graph} 
    vTcl:DefineAlias "$site_3_0.but50" "Button1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but49 \
        -in $site_3_0 -x 0 -relx 0.022 -y 0 -rely 0.316 -width 67 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 0 -relx 0.123 -y 0 -rely 0.316 -width 97 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    label $top.lab48 \
        -background $vTcl(actual_gui_bg) -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) -text Utilities 
    vTcl:DefineAlias "$top.lab48" "Label5" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra45 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.165 -width 0 -relwidth 0.974 \
        -height 0 -relheight 0.416 -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.602 -width 0 -relwidth 0.974 \
        -height 0 -relheight 0.384 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.153 -width 0 -relwidth 0.189 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.033 -y 0 -rely 0.588 -width 0 -relwidth 0.037 \
        -height 0 -relheight 0.029 -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 0 -relx 0.011 -y 0 -rely 0.026 -width 0 -relwidth 0.974 \
        -height 0 -relheight 0.121 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.022 -y 0 -rely 0.013 -width 0 -relwidth 0.048 \
        -height 0 -relheight 0.027 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

